fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
my:
    resource: "@MyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
